language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t satyadeb2000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satyadeb2000/docker-react npm run test -- --coverage
